# monorepo_root = true

[monorepo]
# config_roots = ["e2e-tests"]

[tools]
fnox = "latest"
node = "latest"

[hooks]
postinstall = 'npm install -g corepack'

[settings]
node.corepack = true

[deps]
disable = ["npm", "yarn"]

[deps.pnpm]
auto = true

[env]
# Add node_modules/.bin to PATH
_.path = ['{{config_root}}/node_modules/.bin']
_.file = ".env"
NODE_USE_SYSTEM_CA = "1"

[tasks.dev]
description = 'Run NextJS dev server'
run = 'pnpm dev'

[tasks.download-schema]
description = 'Download the GraphQL schema'
run = 'pnpx @graphql-inspector/cli introspect ${WATCH_BACKEND_URL}/v1/graphql/ --write schema.graphql'

[tasks.portless]
description = "Run the backend with Portless"
run = "portless --name watch-ui --app-port 8052 pnpm dev --webpack"
env = { PORTLESS_WILDCARD = "1", "PORTLESS_TLD" = "test", WILDCARD_DOMAINS = "watch-ui.test" }
raw = true

[tasks.portless-install-service]
description = "Install the Portless service"
run = "portless service install --wildcard --https --tld test"
raw = true
