/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type PlaywrightGetPlanBasicsQuery_plan = { __typename: 'Plan', id: string, identifier: string, primaryLanguage: string, otherLanguages: Array<string> };

export type PlaywrightGetPlanBasicsQuery = { __typename: 'Query', plan: PlaywrightGetPlanBasicsQuery_plan | null };


export type PlaywrightGetPlanBasicsQueryVariables = Exact<{
  plan: string | number;
}>;

export type PlaywrightGetPlanInfoQuery_planOrganizations = { __typename: 'Organization', id: string, name: string };

export type PlaywrightGetPlanInfoQuery_plan_parent = { __typename: 'Plan', identifier: string, name: string };

export type PlaywrightGetPlanInfoQuery_plan_generalContent = { __typename: 'SiteGeneralContent', id: string, siteTitle: string, siteDescription: string };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportType = { __typename: 'ReportType', name: string };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContactFormBlock = { __typename: 'ActionContactFormBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContentAttributeTypeBlock = { __typename: 'ActionContentAttributeTypeBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContentCategoryTypeBlock = { __typename: 'ActionContentCategoryTypeBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContentSectionBlock = { __typename: 'ActionContentSectionBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionDependenciesBlock = { __typename: 'ActionDependenciesBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionDescriptionBlock = { __typename: 'ActionDescriptionBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionLeadParagraphBlock = { __typename: 'ActionLeadParagraphBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionLinksBlock = { __typename: 'ActionLinksBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionMergedActionsBlock = { __typename: 'ActionMergedActionsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionOfficialNameBlock = { __typename: 'ActionOfficialNameBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionPledgesBlock = { __typename: 'ActionPledgesBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionRelatedActionsBlock = { __typename: 'ActionRelatedActionsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionRelatedIndicatorsBlock = { __typename: 'ActionRelatedIndicatorsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionTasksBlock = { __typename: 'ActionTasksBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ChangeLogMessageBlock = { __typename: 'ChangeLogMessageBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_IndicatorCausalChainBlock = { __typename: 'IndicatorCausalChainBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_PlanDatasetsBlock = { __typename: 'PlanDatasetsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock = { __typename: 'ReportComparisonBlock', reportField: string | null, reportType: PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportType | null };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop =
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContactFormBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContentAttributeTypeBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContentCategoryTypeBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionContentSectionBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionDependenciesBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionDescriptionBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionLeadParagraphBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionLinksBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionMergedActionsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionOfficialNameBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionPledgesBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionRelatedActionsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionRelatedIndicatorsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ActionTasksBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ChangeLogMessageBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_IndicatorCausalChainBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_PlanDatasetsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock
;

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportType = { __typename: 'ReportType', name: string };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContactFormBlock = { __typename: 'ActionContactFormBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContentAttributeTypeBlock = { __typename: 'ActionContentAttributeTypeBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContentCategoryTypeBlock = { __typename: 'ActionContentCategoryTypeBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContentSectionBlock = { __typename: 'ActionContentSectionBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionDependenciesBlock = { __typename: 'ActionDependenciesBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionDescriptionBlock = { __typename: 'ActionDescriptionBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionLeadParagraphBlock = { __typename: 'ActionLeadParagraphBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionLinksBlock = { __typename: 'ActionLinksBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionMergedActionsBlock = { __typename: 'ActionMergedActionsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionOfficialNameBlock = { __typename: 'ActionOfficialNameBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionPledgesBlock = { __typename: 'ActionPledgesBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionRelatedActionsBlock = { __typename: 'ActionRelatedActionsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionRelatedIndicatorsBlock = { __typename: 'ActionRelatedIndicatorsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionTasksBlock = { __typename: 'ActionTasksBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ChangeLogMessageBlock = { __typename: 'ChangeLogMessageBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_IndicatorCausalChainBlock = { __typename: 'IndicatorCausalChainBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_PlanDatasetsBlock = { __typename: 'PlanDatasetsBlock' };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock = { __typename: 'ReportComparisonBlock', reportField: string | null, reportType: PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportType | null };

export type PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom =
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContactFormBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContentAttributeTypeBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContentCategoryTypeBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionContentSectionBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionDependenciesBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionDescriptionBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionLeadParagraphBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionLinksBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionMergedActionsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionOfficialNameBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionPledgesBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionRelatedActionsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionRelatedIndicatorsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ActionTasksBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ChangeLogMessageBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_IndicatorCausalChainBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_PlanDatasetsBlock
  | PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock
;

export type PlaywrightGetPlanInfoQuery_plan_actionListPage = { __typename: 'ActionListPage', urlPath: string, includeRelatedPlans: boolean | null, detailsMainTop: Array<PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainTop> | null, detailsMainBottom: Array<PlaywrightGetPlanInfoQuery_plan_actionListPage_detailsMainBottom> | null };

export type PlaywrightGetPlanInfoQuery_plan_actions = { __typename: 'Action', identifier: string, viewUrl: string };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_AccessibilityStatementPage = { __typename: 'AccessibilityStatementPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_ActionListPage = { __typename: 'ActionListPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_CategoryPage = { __typename: 'CategoryPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_CategoryTypePage = { __typename: 'CategoryTypePage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_EmptyPage = { __typename: 'EmptyPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_ImpactGroupPage = { __typename: 'ImpactGroupPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_IndicatorListPage = { __typename: 'IndicatorListPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_Page = { __typename: 'Page', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_PlanRootPage = { __typename: 'PlanRootPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_PledgeListPage = { __typename: 'PledgeListPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_PrivacyPolicyPage = { __typename: 'PrivacyPolicyPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_StaticPage = { __typename: 'StaticPage', id: string | null, title: string, urlPath: string, slug: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page =
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_AccessibilityStatementPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_ActionListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_CategoryPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_CategoryTypePage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_EmptyPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_ImpactGroupPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_IndicatorListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_Page
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_PlanRootPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_PledgeListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_PrivacyPolicyPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page_StaticPage
;

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_AccessibilityStatementPage = { __typename: 'AccessibilityStatementPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_ActionListPage = { __typename: 'ActionListPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_CategoryPage = { __typename: 'CategoryPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_CategoryTypePage = { __typename: 'CategoryTypePage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_EmptyPage = { __typename: 'EmptyPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_ImpactGroupPage = { __typename: 'ImpactGroupPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_IndicatorListPage = { __typename: 'IndicatorListPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_Page = { __typename: 'Page', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_PlanRootPage = { __typename: 'PlanRootPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_PledgeListPage = { __typename: 'PledgeListPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_PrivacyPolicyPage = { __typename: 'PrivacyPolicyPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_StaticPage = { __typename: 'StaticPage', title: string, showInMenus: boolean, live: boolean };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page =
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_AccessibilityStatementPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_ActionListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_CategoryPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_CategoryTypePage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_EmptyPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_ImpactGroupPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_IndicatorListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_Page
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_PlanRootPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_PledgeListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_PrivacyPolicyPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page_StaticPage
;

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent = { __typename: 'PageMenuItem', id: string, page: PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent_page };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_AccessibilityStatementPage = { __typename: 'AccessibilityStatementPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_ActionListPage = { __typename: 'ActionListPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_CategoryPage = { __typename: 'CategoryPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_CategoryTypePage = { __typename: 'CategoryTypePage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_EmptyPage = { __typename: 'EmptyPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_ImpactGroupPage = { __typename: 'ImpactGroupPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_IndicatorListPage = { __typename: 'IndicatorListPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_Page = { __typename: 'Page' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_PlanRootPage = { __typename: 'PlanRootPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_PledgeListPage = { __typename: 'PledgeListPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_PrivacyPolicyPage = { __typename: 'PrivacyPolicyPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_StaticPage = { __typename: 'StaticPage' };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page =
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_AccessibilityStatementPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_ActionListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_CategoryPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_CategoryTypePage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_EmptyPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_ImpactGroupPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_IndicatorListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_Page
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_PlanRootPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_PledgeListPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_PrivacyPolicyPage
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page_StaticPage
;

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children = { __typename: 'PageMenuItem', id: string, page: PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children_page };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_ExternalLinkMenuItem = { __typename: 'ExternalLinkMenuItem', linkText: string, url: string };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem = { __typename: 'PageMenuItem', page: PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_page, parent: PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_parent | null, children: Array<PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem_children> | null };

export type PlaywrightGetPlanInfoQuery_plan_mainMenu_items =
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_ExternalLinkMenuItem
  | PlaywrightGetPlanInfoQuery_plan_mainMenu_items_PageMenuItem
;

export type PlaywrightGetPlanInfoQuery_plan_mainMenu = { __typename: 'MainMenu', items: Array<PlaywrightGetPlanInfoQuery_plan_mainMenu_items> };

export type PlaywrightGetPlanInfoQuery_plan = { __typename: 'Plan', id: string, identifier: string, name: string, shortName: string | null, primaryLanguage: string, otherLanguages: Array<string>, parent: PlaywrightGetPlanInfoQuery_plan_parent | null, generalContent: PlaywrightGetPlanInfoQuery_plan_generalContent, actionListPage: PlaywrightGetPlanInfoQuery_plan_actionListPage | null, actions: Array<PlaywrightGetPlanInfoQuery_plan_actions>, mainMenu: PlaywrightGetPlanInfoQuery_plan_mainMenu | null };

export type PlaywrightGetPlanInfoQuery_planIndicators = { __typename: 'Indicator', id: string, name: string };

export type PlaywrightGetPlanInfoQuery_relatedPlanActions_mergedWith = { __typename: 'Action', viewUrl: string };

export type PlaywrightGetPlanInfoQuery_relatedPlanActions = { __typename: 'Action', identifier: string, viewUrl: string, mergedWith: PlaywrightGetPlanInfoQuery_relatedPlanActions_mergedWith | null };

export type PlaywrightGetPlanInfoQuery = { __typename: 'Query', planOrganizations: Array<PlaywrightGetPlanInfoQuery_planOrganizations> | null, plan: PlaywrightGetPlanInfoQuery_plan | null, planIndicators: Array<PlaywrightGetPlanInfoQuery_planIndicators> | null, relatedPlanActions: Array<PlaywrightGetPlanInfoQuery_relatedPlanActions> | null };


export type PlaywrightGetPlanInfoQueryVariables = Exact<{
  plan: string | number;
  locale: string;
  clientURL: string;
}>;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionAttributeTypeReportFieldBlock = { __typename: 'ActionAttributeTypeReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionCategoryReportFieldBlock = { __typename: 'ActionCategoryReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionDescriptionBlock = { __typename: 'ActionDescriptionBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionEndDateBlock = { __typename: 'ActionEndDateBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionImplementationPhaseReportFieldBlock = { __typename: 'ActionImplementationPhaseReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionManualStatusReasonBlock = { __typename: 'ActionManualStatusReasonBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionPrimaryOrgBlock = { __typename: 'ActionPrimaryOrgBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionRelatedIndicatorsBlock = { __typename: 'ActionRelatedIndicatorsBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionResponsiblePartyReportFieldBlock = { __typename: 'ActionResponsiblePartyReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionScheduleContinuousBlock = { __typename: 'ActionScheduleContinuousBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStartDateBlock = { __typename: 'ActionStartDateBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStatusReportFieldBlock = { __typename: 'ActionStatusReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionTasksBlock = { __typename: 'ActionTasksBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionUpdatedAtBlock = { __typename: 'ActionUpdatedAtBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionAttributeTypeReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionCategoryReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionDescriptionBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionEndDateBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionImplementationPhaseReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionManualStatusReasonBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionPrimaryOrgBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionRelatedIndicatorsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionResponsiblePartyReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionScheduleContinuousBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStartDateBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStatusReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionTasksBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionUpdatedAtBlock
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeCategoryChoice = { __typename: 'AttributeCategoryChoice' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeChoice = { __typename: 'AttributeChoice' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeNumericValue = { __typename: 'AttributeNumericValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeRichText = { __typename: 'AttributeRichText', value: string };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeText = { __typename: 'AttributeText', value: string };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeCategoryChoice
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeChoice
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeNumericValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeRichText
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeText
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionAttributeReportValue = { __typename: 'ActionAttributeReportValue', field: PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_field, attribute: PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionCategoryReportValue = { __typename: 'ActionCategoryReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateFieldReportValue = { __typename: 'ActionDateFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateTimeFieldReportValue = { __typename: 'ActionDateTimeFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionImplementationPhaseReportValue = { __typename: 'ActionImplementationPhaseReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionResponsiblePartyReportValue = { __typename: 'ActionResponsiblePartyReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSimpleFieldReportValue = { __typename: 'ActionSimpleFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSingleRelatedModelFieldReportValue = { __typename: 'ActionSingleRelatedModelFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionStatusReportValue = { __typename: 'ActionStatusReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionTasksReportValue = { __typename: 'ActionTasksReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionAttributeReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionCategoryReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateTimeFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionImplementationPhaseReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionResponsiblePartyReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSimpleFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSingleRelatedModelFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionStatusReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionTasksReportValue
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare = { __typename: 'Report', name: string, valuesForAction: Array<PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare_valuesForAction> | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContactFormBlock = { __typename: 'ActionContactFormBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContentAttributeTypeBlock = { __typename: 'ActionContentAttributeTypeBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContentCategoryTypeBlock = { __typename: 'ActionContentCategoryTypeBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContentSectionBlock = { __typename: 'ActionContentSectionBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionDependenciesBlock = { __typename: 'ActionDependenciesBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionDescriptionBlock = { __typename: 'ActionDescriptionBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionLeadParagraphBlock = { __typename: 'ActionLeadParagraphBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionLinksBlock = { __typename: 'ActionLinksBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionMergedActionsBlock = { __typename: 'ActionMergedActionsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionOfficialNameBlock = { __typename: 'ActionOfficialNameBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionPledgesBlock = { __typename: 'ActionPledgesBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionRelatedActionsBlock = { __typename: 'ActionRelatedActionsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionRelatedIndicatorsBlock = { __typename: 'ActionRelatedIndicatorsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionTasksBlock = { __typename: 'ActionTasksBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ChangeLogMessageBlock = { __typename: 'ChangeLogMessageBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_IndicatorCausalChainBlock = { __typename: 'IndicatorCausalChainBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_PlanDatasetsBlock = { __typename: 'PlanDatasetsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock = { __typename: 'ReportComparisonBlock', reportField: string | null, reportsToCompare: Array<PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock_reportsToCompare | null> | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContactFormBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContentAttributeTypeBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContentCategoryTypeBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionContentSectionBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionDependenciesBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionDescriptionBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionLeadParagraphBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionLinksBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionMergedActionsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionOfficialNameBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionPledgesBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionRelatedActionsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionRelatedIndicatorsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ActionTasksBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ChangeLogMessageBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_IndicatorCausalChainBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_PlanDatasetsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop_ReportComparisonBlock
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionAttributeTypeReportFieldBlock = { __typename: 'ActionAttributeTypeReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionCategoryReportFieldBlock = { __typename: 'ActionCategoryReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionDescriptionBlock = { __typename: 'ActionDescriptionBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionEndDateBlock = { __typename: 'ActionEndDateBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionImplementationPhaseReportFieldBlock = { __typename: 'ActionImplementationPhaseReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionManualStatusReasonBlock = { __typename: 'ActionManualStatusReasonBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionPrimaryOrgBlock = { __typename: 'ActionPrimaryOrgBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionRelatedIndicatorsBlock = { __typename: 'ActionRelatedIndicatorsBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionResponsiblePartyReportFieldBlock = { __typename: 'ActionResponsiblePartyReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionScheduleContinuousBlock = { __typename: 'ActionScheduleContinuousBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStartDateBlock = { __typename: 'ActionStartDateBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStatusReportFieldBlock = { __typename: 'ActionStatusReportFieldBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionTasksBlock = { __typename: 'ActionTasksBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionUpdatedAtBlock = { __typename: 'ActionUpdatedAtBlock', id: string | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionAttributeTypeReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionCategoryReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionDescriptionBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionEndDateBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionImplementationPhaseReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionManualStatusReasonBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionPrimaryOrgBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionRelatedIndicatorsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionResponsiblePartyReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionScheduleContinuousBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStartDateBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionStatusReportFieldBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionTasksBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field_ActionUpdatedAtBlock
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeCategoryChoice = { __typename: 'AttributeCategoryChoice' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeChoice = { __typename: 'AttributeChoice' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeNumericValue = { __typename: 'AttributeNumericValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeRichText = { __typename: 'AttributeRichText', value: string };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeText = { __typename: 'AttributeText', value: string };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeCategoryChoice
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeChoice
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeNumericValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeRichText
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute_AttributeText
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionAttributeReportValue = { __typename: 'ActionAttributeReportValue', field: PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_field, attribute: PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_attribute | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionCategoryReportValue = { __typename: 'ActionCategoryReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateFieldReportValue = { __typename: 'ActionDateFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateTimeFieldReportValue = { __typename: 'ActionDateTimeFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionImplementationPhaseReportValue = { __typename: 'ActionImplementationPhaseReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionResponsiblePartyReportValue = { __typename: 'ActionResponsiblePartyReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSimpleFieldReportValue = { __typename: 'ActionSimpleFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSingleRelatedModelFieldReportValue = { __typename: 'ActionSingleRelatedModelFieldReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionStatusReportValue = { __typename: 'ActionStatusReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionTasksReportValue = { __typename: 'ActionTasksReportValue' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionAttributeReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionCategoryReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionDateTimeFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionImplementationPhaseReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionResponsiblePartyReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSimpleFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionSingleRelatedModelFieldReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionStatusReportValue
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction_ActionTasksReportValue
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare = { __typename: 'Report', name: string, valuesForAction: Array<PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare_valuesForAction> | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContactFormBlock = { __typename: 'ActionContactFormBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContentAttributeTypeBlock = { __typename: 'ActionContentAttributeTypeBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContentCategoryTypeBlock = { __typename: 'ActionContentCategoryTypeBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContentSectionBlock = { __typename: 'ActionContentSectionBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionDependenciesBlock = { __typename: 'ActionDependenciesBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionDescriptionBlock = { __typename: 'ActionDescriptionBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionLeadParagraphBlock = { __typename: 'ActionLeadParagraphBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionLinksBlock = { __typename: 'ActionLinksBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionMergedActionsBlock = { __typename: 'ActionMergedActionsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionOfficialNameBlock = { __typename: 'ActionOfficialNameBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionPledgesBlock = { __typename: 'ActionPledgesBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionRelatedActionsBlock = { __typename: 'ActionRelatedActionsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionRelatedIndicatorsBlock = { __typename: 'ActionRelatedIndicatorsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionTasksBlock = { __typename: 'ActionTasksBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ChangeLogMessageBlock = { __typename: 'ChangeLogMessageBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_IndicatorCausalChainBlock = { __typename: 'IndicatorCausalChainBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_PlanDatasetsBlock = { __typename: 'PlanDatasetsBlock' };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock = { __typename: 'ReportComparisonBlock', reportField: string | null, reportsToCompare: Array<PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock_reportsToCompare | null> | null };

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom =
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContactFormBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContentAttributeTypeBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContentCategoryTypeBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionContentSectionBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionDependenciesBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionDescriptionBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionLeadParagraphBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionLinksBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionMergedActionsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionOfficialNameBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionPledgesBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionRelatedActionsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionRelatedIndicatorsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ActionTasksBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ChangeLogMessageBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_IndicatorCausalChainBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_PlanDatasetsBlock
  | PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom_ReportComparisonBlock
;

export type PlaywrightReportComparisonValuesQuery_plan_actionListPage = { __typename: 'ActionListPage', detailsMainTop: Array<PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainTop> | null, detailsMainBottom: Array<PlaywrightReportComparisonValuesQuery_plan_actionListPage_detailsMainBottom> | null };

export type PlaywrightReportComparisonValuesQuery_plan = { __typename: 'Plan', actionListPage: PlaywrightReportComparisonValuesQuery_plan_actionListPage | null };

export type PlaywrightReportComparisonValuesQuery = { __typename: 'Query', plan: PlaywrightReportComparisonValuesQuery_plan | null };


export type PlaywrightReportComparisonValuesQueryVariables = Exact<{
  plan: string | number;
  action: string | number;
}>;
