/* Generated by scripts/generate-theme-hosts.mjs. Do not edit by hand. */
export const THEME_CSS_HOSTS = [
  'https://api.watch.kausal.tech',
  'https://fast.fonts.net',
  'https://fonts.googleapis.com',
  'https://use.typekit.net',
];

export const ENABLED_INTEGRATION_SETTINGS = [
  'googleAnalyticsId',
  'monsidoToken',
];
